//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by EfmlGen tool using EF Core template.
// Author: HungNM
// Code is generated on: 4/13/2026 6:02:01 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace AllianceMiddlemanWebAPI.Core.Data.Categories
{
    public partial class ConfigState {

        public ConfigState()
        {
            this.IsDeleted = false;
            this.IsDisable = false;
            this.OrderNo = 0;
            OnCreated();
        }

        public virtual long Id { get; set; }

        public virtual string Code { get; set; }

        public virtual string Name { get; set; }

        public virtual bool IsDeleted { get; set; }

        public virtual bool IsDisable { get; set; }

        public virtual DateTimeOffset? Log_CreatedDate { get; set; }

        public virtual string Log_CreatedBy { get; set; }

        public virtual DateTimeOffset? Log_UpdatedDate { get; set; }

        public virtual string Log_UpdatedBy { get; set; }

        public virtual DateTimeOffset? TimeStamp { get; set; }

        public virtual string TimeStampText { get; set; }

        public virtual string Note { get; set; }

        public virtual int OrderNo { get; set; }

        public virtual Guid ID_GUID { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
