//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by EfmlGen tool using EF Core template.
// Author: HungNM
// Code is generated on: 4/13/2026 6:02:01 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata;

namespace AllianceMiddlemanWebAPI.Core.Data.Categories
{

    public partial class CategoryEntities : DbContext
    {

        public CategoryEntities() :
            base()
        {
            OnCreated();
        }

        public CategoryEntities(DbContextOptions<CategoryEntities> options) :
            base(options)
        {
            OnCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured ||
                (!optionsBuilder.Options.Extensions.OfType<RelationalOptionsExtension>().Any(ext => !string.IsNullOrEmpty(ext.ConnectionString) || ext.Connection != null) &&
                 !optionsBuilder.Options.Extensions.Any(ext => !(ext is RelationalOptionsExtension) && !(ext is CoreOptionsExtension))))
            {
                optionsBuilder.UseNpgsql(@"Host=160.22.122.239;Username=udb;Password=;Database=CoShareTest");
            }
            CustomizeConfiguration(ref optionsBuilder);
            base.OnConfiguring(optionsBuilder);
        }

        partial void CustomizeConfiguration(ref DbContextOptionsBuilder optionsBuilder);

        public virtual DbSet<ConfigState> ConfigState
        {
            get;
            set;
        }

        public virtual DbSet<ConfigReportOrderReason> ConfigReportOrderReason
        {
            get;
            set;
        }

        public virtual DbSet<ConfigReportUserReason> ConfigReportUserReason
        {
            get;
            set;
        }

        public virtual DbSet<ConfigRentalServiceRatingPoint> ConfigRentalServiceRatingPoint
        {
            get;
            set;
        }

        public virtual DbSet<Mioto_VehicleOwner> Mioto_VehicleOwner
        {
            get;
            set;
        }

        public virtual DbSet<Department> Department
        {
            get;
            set;
        }

        public virtual DbSet<Product_Company_Mapping> Product_Company_Mapping
        {
            get;
            set;
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            this.ConfigStateMapping(modelBuilder);
            this.CustomizeConfigStateMapping(modelBuilder);

            this.ConfigReportOrderReasonMapping(modelBuilder);
            this.CustomizeConfigReportOrderReasonMapping(modelBuilder);

            this.ConfigReportUserReasonMapping(modelBuilder);
            this.CustomizeConfigReportUserReasonMapping(modelBuilder);

            this.ConfigRentalServiceRatingPointMapping(modelBuilder);
            this.CustomizeConfigRentalServiceRatingPointMapping(modelBuilder);

            this.Mioto_VehicleOwnerMapping(modelBuilder);
            this.CustomizeMioto_VehicleOwnerMapping(modelBuilder);

            this.DepartmentMapping(modelBuilder);
            this.CustomizeDepartmentMapping(modelBuilder);

            this.Product_Company_MappingMapping(modelBuilder);
            this.CustomizeProduct_Company_MappingMapping(modelBuilder);

            RelationshipsMapping(modelBuilder);
            CustomizeMapping(ref modelBuilder);
        }

        #region ConfigState Mapping

        private void ConfigStateMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ConfigState>().ToTable(@"ConfigState", @"dbo");
            modelBuilder.Entity<ConfigState>().Property(x => x.Id).HasColumnName(@"Id").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<ConfigState>().Property(x => x.Code).HasColumnName(@"Code").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<ConfigState>().Property(x => x.Name).HasColumnName(@"Name").ValueGeneratedNever();
            modelBuilder.Entity<ConfigState>().Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<ConfigState>().Property(x => x.IsDisable).HasColumnName(@"IsDisable").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<ConfigState>().Property(x => x.Log_CreatedDate).HasColumnName(@"Log_CreatedDate").ValueGeneratedNever();
            modelBuilder.Entity<ConfigState>().Property(x => x.Log_CreatedBy).HasColumnName(@"Log_CreatedBy").ValueGeneratedNever();
            modelBuilder.Entity<ConfigState>().Property(x => x.Log_UpdatedDate).HasColumnName(@"Log_UpdatedDate").ValueGeneratedNever();
            modelBuilder.Entity<ConfigState>().Property(x => x.Log_UpdatedBy).HasColumnName(@"Log_UpdatedBy").ValueGeneratedNever();
            modelBuilder.Entity<ConfigState>().Property(x => x.TimeStamp).HasColumnName(@"TimeStamp").ValueGeneratedNever();
            modelBuilder.Entity<ConfigState>().Property(x => x.TimeStampText).HasColumnName(@"TimeStampText").ValueGeneratedNever();
            modelBuilder.Entity<ConfigState>().Property(x => x.Note).HasColumnName(@"Note").ValueGeneratedNever();
            modelBuilder.Entity<ConfigState>().Property(x => x.OrderNo).HasColumnName(@"OrderNo").HasColumnType(@"int4").IsRequired().ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<ConfigState>().Property(x => x.ID_GUID).HasColumnName(@"ID_GUID").HasColumnType(@"uuid").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"uuid_generate_v7()");
            modelBuilder.Entity<ConfigState>().HasKey(@"Id");
        }

        partial void CustomizeConfigStateMapping(ModelBuilder modelBuilder);

        #endregion

        #region ConfigReportOrderReason Mapping

        private void ConfigReportOrderReasonMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ConfigReportOrderReason>().ToTable(@"ConfigReportOrderReason", @"dbo");
            modelBuilder.Entity<ConfigReportOrderReason>().Property(x => x.Id).HasColumnName(@"Id").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<ConfigReportOrderReason>().Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType(@"bool").IsRequired().ValueGeneratedNever().HasDefaultValueSql(@"false");
            modelBuilder.Entity<ConfigReportOrderReason>().Property(x => x.Log_CreatedDate).HasColumnName(@"Log_CreatedDate").ValueGeneratedNever();
            modelBuilder.Entity<ConfigReportOrderReason>().Property(x => x.Log_CreatedBy).HasColumnName(@"Log_CreatedBy").ValueGeneratedNever().HasMaxLength(500);
            modelBuilder.Entity<ConfigReportOrderReason>().Property(x => x.Log_UpdatedDate).HasColumnName(@"Log_UpdatedDate").ValueGeneratedNever();
            modelBuilder.Entity<ConfigReportOrderReason>().Property(x => x.Log_UpdatedBy).HasColumnName(@"Log_UpdatedBy").ValueGeneratedNever().HasMaxLength(500);
            modelBuilder.Entity<ConfigReportOrderReason>().Property(x => x.Note).HasColumnName(@"Note").ValueGeneratedNever();
            modelBuilder.Entity<ConfigReportOrderReason>().Property(x => x.OrderNo).HasColumnName(@"OrderNo").HasColumnType(@"numeric").IsRequired().ValueGeneratedNever().HasPrecision(20, 6).HasDefaultValueSql(@"0");
            modelBuilder.Entity<ConfigReportOrderReason>().Property(x => x.IsDisable).HasColumnName(@"IsDisable").HasColumnType(@"bool").IsRequired().ValueGeneratedNever().HasDefaultValueSql(@"false");
            modelBuilder.Entity<ConfigReportOrderReason>().Property(x => x.Code).HasColumnName(@"Code").ValueGeneratedNever();
            modelBuilder.Entity<ConfigReportOrderReason>().Property(x => x.Name).HasColumnName(@"Name").ValueGeneratedNever();
            modelBuilder.Entity<ConfigReportOrderReason>().Property(x => x.Description).HasColumnName(@"Description").ValueGeneratedNever();
            modelBuilder.Entity<ConfigReportOrderReason>().Property(x => x.ColorCode).HasColumnName(@"ColorCode").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<ConfigReportOrderReason>().Property(x => x.IconUrl).HasColumnName(@"IconUrl").ValueGeneratedNever();
            modelBuilder.Entity<ConfigReportOrderReason>().Property(x => x.IsShowExtReason).HasColumnName(@"IsShowExtReason").HasColumnType(@"bool").IsRequired().ValueGeneratedNever().HasDefaultValueSql(@"false");
            modelBuilder.Entity<ConfigReportOrderReason>().Property(x => x.ID_GUID).HasColumnName(@"ID_GUID").HasColumnType(@"uuid").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"uuid_generate_v7()");
            modelBuilder.Entity<ConfigReportOrderReason>().HasKey(@"Id");
        }

        partial void CustomizeConfigReportOrderReasonMapping(ModelBuilder modelBuilder);

        #endregion

        #region ConfigReportUserReason Mapping

        private void ConfigReportUserReasonMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ConfigReportUserReason>().ToTable(@"ConfigReportUserReason", @"dbo");
            modelBuilder.Entity<ConfigReportUserReason>().Property(x => x.Id).HasColumnName(@"Id").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<ConfigReportUserReason>().Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType(@"bool").IsRequired().ValueGeneratedNever().HasDefaultValueSql(@"false");
            modelBuilder.Entity<ConfigReportUserReason>().Property(x => x.Log_CreatedDate).HasColumnName(@"Log_CreatedDate").ValueGeneratedNever();
            modelBuilder.Entity<ConfigReportUserReason>().Property(x => x.Log_CreatedBy).HasColumnName(@"Log_CreatedBy").ValueGeneratedNever().HasMaxLength(500);
            modelBuilder.Entity<ConfigReportUserReason>().Property(x => x.Log_UpdatedDate).HasColumnName(@"Log_UpdatedDate").ValueGeneratedNever();
            modelBuilder.Entity<ConfigReportUserReason>().Property(x => x.Log_UpdatedBy).HasColumnName(@"Log_UpdatedBy").ValueGeneratedNever().HasMaxLength(500);
            modelBuilder.Entity<ConfigReportUserReason>().Property(x => x.Note).HasColumnName(@"Note").ValueGeneratedNever();
            modelBuilder.Entity<ConfigReportUserReason>().Property(x => x.OrderNo).HasColumnName(@"OrderNo").HasColumnType(@"numeric").IsRequired().ValueGeneratedNever().HasPrecision(20, 6).HasDefaultValueSql(@"0");
            modelBuilder.Entity<ConfigReportUserReason>().Property(x => x.IsDisable).HasColumnName(@"IsDisable").HasColumnType(@"bool").IsRequired().ValueGeneratedNever().HasDefaultValueSql(@"false");
            modelBuilder.Entity<ConfigReportUserReason>().Property(x => x.Code).HasColumnName(@"Code").ValueGeneratedNever();
            modelBuilder.Entity<ConfigReportUserReason>().Property(x => x.Name).HasColumnName(@"Name").ValueGeneratedNever();
            modelBuilder.Entity<ConfigReportUserReason>().Property(x => x.Description).HasColumnName(@"Description").ValueGeneratedNever();
            modelBuilder.Entity<ConfigReportUserReason>().Property(x => x.ColorCode).HasColumnName(@"ColorCode").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<ConfigReportUserReason>().Property(x => x.IconUrl).HasColumnName(@"IconUrl").ValueGeneratedNever();
            modelBuilder.Entity<ConfigReportUserReason>().Property(x => x.ShowExtReason).HasColumnName(@"ShowExtReason").ValueGeneratedNever();
            modelBuilder.Entity<ConfigReportUserReason>().Property(x => x.ID_GUID).HasColumnName(@"ID_GUID").HasColumnType(@"uuid").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"uuid_generate_v7()");
            modelBuilder.Entity<ConfigReportUserReason>().HasKey(@"Id");
        }

        partial void CustomizeConfigReportUserReasonMapping(ModelBuilder modelBuilder);

        #endregion

        #region ConfigRentalServiceRatingPoint Mapping

        private void ConfigRentalServiceRatingPointMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ConfigRentalServiceRatingPoint>().ToTable(@"ConfigRentalServiceRatingPoint", @"dbo");
            modelBuilder.Entity<ConfigRentalServiceRatingPoint>().Property(x => x.Id).HasColumnName(@"Id").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<ConfigRentalServiceRatingPoint>().Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType(@"bool").IsRequired().ValueGeneratedNever().HasDefaultValueSql(@"false");
            modelBuilder.Entity<ConfigRentalServiceRatingPoint>().Property(x => x.Log_CreatedDate).HasColumnName(@"Log_CreatedDate").ValueGeneratedNever();
            modelBuilder.Entity<ConfigRentalServiceRatingPoint>().Property(x => x.Log_CreatedBy).HasColumnName(@"Log_CreatedBy").ValueGeneratedNever().HasMaxLength(500);
            modelBuilder.Entity<ConfigRentalServiceRatingPoint>().Property(x => x.Log_UpdatedDate).HasColumnName(@"Log_UpdatedDate").ValueGeneratedNever();
            modelBuilder.Entity<ConfigRentalServiceRatingPoint>().Property(x => x.Log_UpdatedBy).HasColumnName(@"Log_UpdatedBy").ValueGeneratedNever().HasMaxLength(500);
            modelBuilder.Entity<ConfigRentalServiceRatingPoint>().Property(x => x.Note).HasColumnName(@"Note").ValueGeneratedNever();
            modelBuilder.Entity<ConfigRentalServiceRatingPoint>().Property(x => x.OrderNo).HasColumnName(@"OrderNo").HasColumnType(@"numeric").IsRequired().ValueGeneratedNever().HasPrecision(20, 6).HasDefaultValueSql(@"0");
            modelBuilder.Entity<ConfigRentalServiceRatingPoint>().Property(x => x.IsDisable).HasColumnName(@"IsDisable").HasColumnType(@"bool").IsRequired().ValueGeneratedNever().HasDefaultValueSql(@"false");
            modelBuilder.Entity<ConfigRentalServiceRatingPoint>().Property(x => x.Code).HasColumnName(@"Code").ValueGeneratedNever();
            modelBuilder.Entity<ConfigRentalServiceRatingPoint>().Property(x => x.Name).HasColumnName(@"Name").ValueGeneratedNever();
            modelBuilder.Entity<ConfigRentalServiceRatingPoint>().Property(x => x.Description).HasColumnName(@"Description").ValueGeneratedNever();
            modelBuilder.Entity<ConfigRentalServiceRatingPoint>().Property(x => x.ColorCode).HasColumnName(@"ColorCode").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<ConfigRentalServiceRatingPoint>().Property(x => x.IconUrl).HasColumnName(@"IconUrl").ValueGeneratedNever();
            modelBuilder.Entity<ConfigRentalServiceRatingPoint>().Property(x => x.Rating).HasColumnName(@"Rating").ValueGeneratedNever().HasPrecision(18, 3);
            modelBuilder.Entity<ConfigRentalServiceRatingPoint>().Property(x => x.ID_GUID).HasColumnName(@"ID_GUID").HasColumnType(@"uuid").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"uuid_generate_v7()");
            modelBuilder.Entity<ConfigRentalServiceRatingPoint>().HasKey(@"Id");
        }

        partial void CustomizeConfigRentalServiceRatingPointMapping(ModelBuilder modelBuilder);

        #endregion

        #region Mioto_VehicleOwner Mapping

        private void Mioto_VehicleOwnerMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Mioto_VehicleOwner>().ToTable(@"Mioto_VehicleOwner", @"dbo");
            modelBuilder.Entity<Mioto_VehicleOwner>().Property(x => x.Id).HasColumnName(@"Id").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<Mioto_VehicleOwner>().Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType(@"bool").IsRequired().ValueGeneratedNever().HasDefaultValueSql(@"false");
            modelBuilder.Entity<Mioto_VehicleOwner>().Property(x => x.Log_CreatedDate).HasColumnName(@"Log_CreatedDate").ValueGeneratedNever();
            modelBuilder.Entity<Mioto_VehicleOwner>().Property(x => x.Log_CreatedBy).HasColumnName(@"Log_CreatedBy").ValueGeneratedNever().HasMaxLength(500);
            modelBuilder.Entity<Mioto_VehicleOwner>().Property(x => x.Log_UpdatedDate).HasColumnName(@"Log_UpdatedDate").ValueGeneratedNever();
            modelBuilder.Entity<Mioto_VehicleOwner>().Property(x => x.Log_UpdatedBy).HasColumnName(@"Log_UpdatedBy").ValueGeneratedNever().HasMaxLength(500);
            modelBuilder.Entity<Mioto_VehicleOwner>().Property(x => x.Note).HasColumnName(@"Note").ValueGeneratedNever();
            modelBuilder.Entity<Mioto_VehicleOwner>().Property(x => x.OrderNo).HasColumnName(@"OrderNo").HasColumnType(@"numeric").IsRequired().ValueGeneratedNever().HasPrecision(20, 6).HasDefaultValueSql(@"0");
            modelBuilder.Entity<Mioto_VehicleOwner>().Property(x => x.IsDisable).HasColumnName(@"IsDisable").HasColumnType(@"bool").IsRequired().ValueGeneratedNever().HasDefaultValueSql(@"false");
            modelBuilder.Entity<Mioto_VehicleOwner>().Property(x => x.Code).HasColumnName(@"Code").ValueGeneratedNever();
            modelBuilder.Entity<Mioto_VehicleOwner>().Property(x => x.Name).HasColumnName(@"Name").ValueGeneratedNever();
            modelBuilder.Entity<Mioto_VehicleOwner>().Property(x => x.Description).HasColumnName(@"Description").ValueGeneratedNever();
            modelBuilder.Entity<Mioto_VehicleOwner>().Property(x => x.ColorCode).HasColumnName(@"ColorCode").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Mioto_VehicleOwner>().Property(x => x.IconUrl).HasColumnName(@"IconUrl").ValueGeneratedNever();
            modelBuilder.Entity<Mioto_VehicleOwner>().Property(x => x.NameUnsign).HasColumnName(@"NameUnsign").ValueGeneratedNever();
            modelBuilder.Entity<Mioto_VehicleOwner>().Property(x => x.ID_GUID).HasColumnName(@"ID_GUID").HasColumnType(@"uuid").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"uuid_generate_v7()");
            modelBuilder.Entity<Mioto_VehicleOwner>().HasKey(@"Id");
        }

        partial void CustomizeMioto_VehicleOwnerMapping(ModelBuilder modelBuilder);

        #endregion

        #region Department Mapping

        private void DepartmentMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Department>().ToTable(@"Department", @"dbo");
            modelBuilder.Entity<Department>().Property(x => x.Id).HasColumnName(@"Id").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<Department>().Property(x => x.Code).HasColumnName(@"Code").IsRequired().ValueGeneratedNever().HasMaxLength(250);
            modelBuilder.Entity<Department>().Property(x => x.Name).HasColumnName(@"Name").ValueGeneratedNever().HasMaxLength(500);
            modelBuilder.Entity<Department>().Property(x => x.OrderNo).HasColumnName(@"OrderNo").HasColumnType(@"int4").IsRequired().ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<Department>().Property(x => x.ParentId).HasColumnName(@"ParentId").ValueGeneratedNever();
            modelBuilder.Entity<Department>().Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType(@"bool").IsRequired().ValueGeneratedNever().HasDefaultValueSql(@"false");
            modelBuilder.Entity<Department>().Property(x => x.Log_CreatedDate).HasColumnName(@"Log_CreatedDate").ValueGeneratedNever();
            modelBuilder.Entity<Department>().Property(x => x.Log_CreatedBy).HasColumnName(@"Log_CreatedBy").ValueGeneratedNever().HasMaxLength(500);
            modelBuilder.Entity<Department>().Property(x => x.Log_UpdatedDate).HasColumnName(@"Log_UpdatedDate").ValueGeneratedNever();
            modelBuilder.Entity<Department>().Property(x => x.Log_UpdatedBy).HasColumnName(@"Log_UpdatedBy").ValueGeneratedNever().HasMaxLength(500);
            modelBuilder.Entity<Department>().Property(x => x.IsDisable).HasColumnName(@"IsDisable").HasColumnType(@"bool").IsRequired().ValueGeneratedNever().HasDefaultValueSql(@"false");
            modelBuilder.Entity<Department>().Property(x => x.ColorCode).HasColumnName(@"ColorCode").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Department>().Property(x => x.DisplayName).HasColumnName(@"DisplayName").ValueGeneratedNever().HasMaxLength(250);
            modelBuilder.Entity<Department>().Property(x => x.Note).HasColumnName(@"Note").ValueGeneratedNever();
            modelBuilder.Entity<Department>().Property(x => x.AllowCreatePassword).HasColumnName(@"AllowCreatePassword").HasColumnType(@"bool").IsRequired().ValueGeneratedNever().HasDefaultValueSql(@"false");
            modelBuilder.Entity<Department>().Property(x => x.CompanyId).HasColumnName(@"CompanyId").ValueGeneratedNever();
            modelBuilder.Entity<Department>().Property(x => x.IsReadOnly).HasColumnName(@"IsReadOnly").HasColumnType(@"bool").IsRequired().ValueGeneratedNever().HasDefaultValueSql(@"false");
            modelBuilder.Entity<Department>().Property(x => x.TimeStamp).HasColumnName(@"TimeStamp").ValueGeneratedNever();
            modelBuilder.Entity<Department>().Property(x => x.TimeStampText).HasColumnName(@"TimeStampText").ValueGeneratedNever();
            modelBuilder.Entity<Department>().Property(x => x.JoinToOrgChart).HasColumnName(@"JoinToOrgChart").HasColumnType(@"bool").IsRequired().ValueGeneratedNever().HasDefaultValueSql(@"false");
            modelBuilder.Entity<Department>().Property(x => x.ID_GUID).HasColumnName(@"ID_GUID").HasColumnType(@"uuid").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"uuid_generate_v7()");
            modelBuilder.Entity<Department>().HasKey(@"Id");
        }

        partial void CustomizeDepartmentMapping(ModelBuilder modelBuilder);

        #endregion

        #region Product_Company_Mapping Mapping

        private void Product_Company_MappingMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Product_Company_Mapping>().ToTable(@"Product_Company_Mapping", @"dbo");
            modelBuilder.Entity<Product_Company_Mapping>().Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Product_Company_Mapping>().Property(x => x.Log_CreatedDate).HasColumnName(@"Log_CreatedDate").ValueGeneratedNever();
            modelBuilder.Entity<Product_Company_Mapping>().Property(x => x.Log_CreatedBy).HasColumnName(@"Log_CreatedBy").ValueGeneratedNever().HasMaxLength(500);
            modelBuilder.Entity<Product_Company_Mapping>().Property(x => x.Log_UpdatedDate).HasColumnName(@"Log_UpdatedDate").ValueGeneratedNever();
            modelBuilder.Entity<Product_Company_Mapping>().Property(x => x.Log_UpdatedBy).HasColumnName(@"Log_UpdatedBy").ValueGeneratedNever().HasMaxLength(500);
            modelBuilder.Entity<Product_Company_Mapping>().Property(x => x.Note).HasColumnName(@"Note").ValueGeneratedNever();
            modelBuilder.Entity<Product_Company_Mapping>().Property(x => x.OrderNo).HasColumnName(@"OrderNo").IsRequired().ValueGeneratedNever().HasPrecision(20, 6);
            modelBuilder.Entity<Product_Company_Mapping>().Property(x => x.IsDisable).HasColumnName(@"IsDisable").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Product_Company_Mapping>().Property(x => x.Code).HasColumnName(@"Code").ValueGeneratedNever();
            modelBuilder.Entity<Product_Company_Mapping>().Property(x => x.Name).HasColumnName(@"Name").ValueGeneratedNever();
            modelBuilder.Entity<Product_Company_Mapping>().Property(x => x.Description).HasColumnName(@"Description").ValueGeneratedNever();
            modelBuilder.Entity<Product_Company_Mapping>().Property(x => x.ColorCode).HasColumnName(@"ColorCode").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Product_Company_Mapping>().Property(x => x.IconUrl).HasColumnName(@"IconUrl").ValueGeneratedNever();
            modelBuilder.Entity<Product_Company_Mapping>().Property(x => x.Id).HasColumnName(@"Id").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<Product_Company_Mapping>().Property(x => x.ID_GUID).HasColumnName(@"ID_GUID").IsRequired().ValueGeneratedOnAdd();
            modelBuilder.Entity<Product_Company_Mapping>().Property(x => x.MerchantProductGUID).HasColumnName(@"MerchantProductGUID").ValueGeneratedNever();
            modelBuilder.Entity<Product_Company_Mapping>().Property(x => x.CompanyGUID).HasColumnName(@"CompanyGUID").ValueGeneratedNever();
            modelBuilder.Entity<Product_Company_Mapping>().Property(x => x.ValidFrom).HasColumnName(@"ValidFrom").ValueGeneratedNever();
            modelBuilder.Entity<Product_Company_Mapping>().Property(x => x.ExpiredAt).HasColumnName(@"ExpiredAt").ValueGeneratedNever();
            modelBuilder.Entity<Product_Company_Mapping>().Property(x => x.Images).HasColumnName(@"Images").ValueGeneratedNever();
            modelBuilder.Entity<Product_Company_Mapping>().Property(x => x.MoreConfig).HasColumnName(@"MoreConfig").ValueGeneratedNever();
            modelBuilder.Entity<Product_Company_Mapping>().HasKey(@"Id");
        }

        partial void CustomizeProduct_Company_MappingMapping(ModelBuilder modelBuilder);

        #endregion

        private void RelationshipsMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Department>().HasMany(x => x.Department_ParentId1).WithOne(op => op.Department_ParentId).HasForeignKey(@"ParentId").IsRequired(false);
            modelBuilder.Entity<Department>().HasOne(x => x.Department_ParentId).WithMany(op => op.Department_ParentId1).HasForeignKey(@"ParentId").IsRequired(false);
        }

        partial void CustomizeMapping(ref ModelBuilder modelBuilder);

        public bool HasChanges()
        {
            return ChangeTracker.Entries().Any(e => e.State == Microsoft.EntityFrameworkCore.EntityState.Added || e.State == Microsoft.EntityFrameworkCore.EntityState.Modified || e.State == Microsoft.EntityFrameworkCore.EntityState.Deleted);
        }

        partial void OnCreated();
    }
}
