//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by EfmlGen tool using EF Core template.
// Author: HungNM
// Code is generated on: 5/18/2026 10:00:00 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace SampleApp.Data.Categories
{
    public partial class Department {

        public Department()
        {
            this.OrderNo = 0;
            this.IsDeleted = false;
            this.IsDisable = false;
            this.AllowCreatePassword = false;
            this.IsReadOnly = false;
            this.JoinToOrgChart = false;
            this.Department_ParentId1 = new List<Department>();
            OnCreated();
        }

        public virtual long Id { get; set; }

        public virtual string Code { get; set; }

        public virtual string Name { get; set; }

        public virtual int OrderNo { get; set; }

        public virtual long? ParentId { get; set; }

        public virtual bool IsDeleted { get; set; }

        public virtual DateTimeOffset? Log_CreatedDate { get; set; }

        public virtual string Log_CreatedBy { get; set; }

        public virtual DateTimeOffset? Log_UpdatedDate { get; set; }

        public virtual string Log_UpdatedBy { get; set; }

        public virtual bool IsDisable { get; set; }

        public virtual string ColorCode { get; set; }

        public virtual string DisplayName { get; set; }

        public virtual string Note { get; set; }

        public virtual bool AllowCreatePassword { get; set; }

        public virtual long? CompanyId { get; set; }

        public virtual bool IsReadOnly { get; set; }

        public virtual byte[] TimeStamp { get; set; }

        public virtual string TimeStampText { get; set; }

        public virtual bool JoinToOrgChart { get; set; }

        public virtual Guid ID_GUID { get; set; }

        public virtual IList<Department> Department_ParentId1 { get; set; }

        public virtual Department Department_ParentId { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
