using System.Text;

namespace EfmlGen.Templates;

internal static class HeaderEmitter
{
    public static void Write(StringBuilder sb, GenerationContext ctx)
    {
        sb.Append("//------------------------------------------------------------------------------\r\n");
        sb.Append("// This is auto-generated code.\r\n");
        sb.Append("//------------------------------------------------------------------------------\r\n");
        sb.Append("// This code was generated by EfmlGen tool using EF Core template.\r\n");
        sb.Append("// Author: HungNM\r\n");
        sb.Append("// Code is generated on: ").Append(ctx.FormattedTimestamp).Append("\r\n");
        sb.Append("//\r\n");
        sb.Append("// Changes to this file may cause incorrect behavior and will be lost if\r\n");
        sb.Append("// the code is regenerated.\r\n");
        sb.Append("//------------------------------------------------------------------------------\r\n");
        sb.Append("\r\n");
    }
}
